[culls]
west = false
east = false
south = false
north = false
down = false
up = false

[[parts]]
type = "cuboid"
west = { tile = "leaves.png" }
east = { tile = "leaves.png" }
south = { tile = "leaves.png" }
north = { tile = "leaves.png" }
down = { tile = "leaves.png" }
up = { tile = "leaves.png" }
